// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: encryption.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum DataMessage_Type

typedef GPB_ENUM(DataMessage_Type) {
  DataMessage_Type_Somessagetypetext = 0,
  DataMessage_Type_Somessagetypephoto = 1,
  DataMessage_Type_Somessagetypevideo = 2,
};

GPBEnumDescriptor *DataMessage_Type_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL DataMessage_Type_IsValidValue(int32_t value);

#pragma mark - EncryptionRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface EncryptionRoot : GPBRootObject
@end

#pragma mark - DataMessage

typedef GPB_ENUM(DataMessage_FieldNumber) {
  DataMessage_FieldNumber_Recipient = 1,
  DataMessage_FieldNumber_Sender = 2,
  DataMessage_FieldNumber_Body = 3,
  DataMessage_FieldNumber_Attachment = 4,
};

@interface DataMessage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *recipient;
/** Test to see if @c recipient has been set. */
@property(nonatomic, readwrite) BOOL hasRecipient;

@property(nonatomic, readwrite, copy, null_resettable) NSString *sender;
/** Test to see if @c sender has been set. */
@property(nonatomic, readwrite) BOOL hasSender;

@property(nonatomic, readwrite, copy, null_resettable) NSString *body;
/** Test to see if @c body has been set. */
@property(nonatomic, readwrite) BOOL hasBody;

@property(nonatomic, readwrite) BOOL attachment;

@property(nonatomic, readwrite) BOOL hasAttachment;
@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
