// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: profiles.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class Person;
@class Text;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - ProfilesRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface ProfilesRoot : GPBRootObject
@end

#pragma mark - Person

typedef GPB_ENUM(Person_FieldNumber) {
  Person_FieldNumber_Name = 1,
  Person_FieldNumber_PhoneNumber = 2,
};

@interface Person : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;
/** Test to see if @c name has been set. */
@property(nonatomic, readwrite) BOOL hasName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *phoneNumber;
/** Test to see if @c phoneNumber has been set. */
@property(nonatomic, readwrite) BOOL hasPhoneNumber;

@end

#pragma mark - Text

typedef GPB_ENUM(Text_FieldNumber) {
  Text_FieldNumber_Message = 1,
};

@interface Text : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *message;
/** Test to see if @c message has been set. */
@property(nonatomic, readwrite) BOOL hasMessage;

@end

#pragma mark - Contacts

typedef GPB_ENUM(Contacts_FieldNumber) {
  Contacts_FieldNumber_PeopleArray = 1,
};

@interface Contacts : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Person*> *peopleArray;
/** The number of items in @c peopleArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger peopleArray_Count;

@end

#pragma mark - Chat

typedef GPB_ENUM(Chat_FieldNumber) {
  Chat_FieldNumber_MessagesArray = 1,
};

@interface Chat : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Text*> *messagesArray;
/** The number of items in @c messagesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger messagesArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
